version: '3.8'

services:
  chat-api:
    container_name: chat-rag-personal-classifier-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - PORT=3000
      - NODE_ENV=development
    restart: unless-stopped
