name: Keep API Alive

on:
  schedule:
    # Runs every 14 minutes between 08:00 and 17:58 UTC to prevent Railway from sleeping
    - cron: '*/14 8-17 * * *'
  workflow_dispatch: # Allows manual execution from the Actions tab

jobs:
  ping-api:
    runs-on: ubuntu-latest
    steps:
      - name: 🏓 Waking up Classifier API
        continue-on-error: true
        run: |
          echo "Sending ping to API Health Check route..."
          curl -sL https://api.maioli.dev.br/ping > /dev/null
          echo "Ping sent successfully."
